"use client";
import { useEffect, useState } from "react";
import api from "@/lib/api";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  CalendarDays,
  Clock,
  FileText,
  Loader2,
  Sparkles,
  Copy,
  Check,
  X,
  ClipboardList,
  AlertTriangle,
} from "lucide-react";
import { toast } from "sonner";

interface SOAPResult {
  subjective: string;
  objective: string;
  assessment: string;
  plan: string;
  summary: string;
}

export default function DoctorAppointments() {
  const [a, setA] = useState<any[]>([]);

  // AI Scribe state
  const [activeScribeId, setActiveScribeId] = useState<string | null>(null);
  const [scribeNotes, setScribeNotes] = useState("");
  const [soapResult, setSoapResult] = useState<SOAPResult | null>(null);
  const [scribeLoading, setScribeLoading] = useState(false);
  const [scribeError, setScribeError] = useState("");
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    api
      .get("/appointments/my")
      .then((r) => {
        const sorted = [...r.data].sort((a: any, b: any) => {
          const diff =
            new Date(b.appointmentDate).getTime() -
            new Date(a.appointmentDate).getTime();
          if (diff !== 0) return diff;
          return b.timeSlot.localeCompare(a.timeSlot); // same date → later time first
        });
        setA(sorted);
      })
      .catch(() => {});
  }, []);

  const upd = async (id: string, s: string) => {
    try {
      await api.patch(`/appointments/${id}/status`, { status: s });
      setA((x) => x.map((z) => (z.id === id ? { ...z, status: s } : z)));
      toast.success("Updated");
    } catch {
      toast.error("Failed");
    }
  };

  const toggleScribe = (id: string) => {
    if (activeScribeId === id) {
      setActiveScribeId(null);
      setScribeNotes("");
      setSoapResult(null);
      setScribeError("");
    } else {
      setActiveScribeId(id);
      setScribeNotes("");
      setSoapResult(null);
      setScribeError("");
    }
  };

  const generateSOAP = async () => {
    if (!scribeNotes.trim() || scribeNotes.trim().length < 10) {
      setScribeError("Please enter more detailed consultation notes.");
      return;
    }
    setScribeLoading(true);
    setScribeError("");
    setSoapResult(null);

    const apt = a.find((x) => x.id === activeScribeId);

    try {
      const res = await fetch("/api/ai/soap", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          notes: scribeNotes.trim(),
          patientInfo: apt
            ? `Appointment reason: ${apt.reason}, Date: ${apt.appointmentDate}, Time: ${apt.timeSlot}`
            : undefined,
        }),
      });
      const data = await res.json();
      if (!res.ok) {
        setScribeError(data.error || "Failed to generate SOAP note.");
      } else {
        setSoapResult(data);
      }
    } catch {
      setScribeError("Could not connect to the AI service. Please try again.");
    } finally {
      setScribeLoading(false);
    }
  };

  const copySOAP = () => {
    if (!soapResult) return;
    const text = `SOAP CLINICAL NOTE\n${"═".repeat(40)}\n\nSUBJECTIVE:\n${soapResult.subjective}\n\nOBJECTIVE:\n${soapResult.objective}\n\nASSESSMENT:\n${soapResult.assessment}\n\nPLAN:\n${soapResult.plan}\n\n${"─".repeat(40)}\nSummary: ${soapResult.summary}\nGenerated by NexusHealth AI Medical Scribe`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    toast.success("SOAP note copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  const sc: Record<string, string> = {
    PENDING_PAYMENT: "bg-amber-50 text-amber-600",
    CONFIRMED: "bg-emerald-50 text-emerald-600",
    IN_PROGRESS: "bg-blue-50 text-blue-600",
    COMPLETED: "bg-slate-100 text-slate-500",
    CANCELLED: "bg-red-50 text-red-500",
  };

  return (
    <div>
      <h1 className="text-2xl font-bold text-slate-900 mb-8">Appointments</h1>
      {a.length === 0 ? (
        <p className="text-slate-400 text-center py-20">No appointments</p>
      ) : (
        <div className="space-y-3">
          {a.map((apt) => (
            <div key={apt.id}>
              <Card
                className={`bg-white border-slate-200/80 shadow-sm hover:shadow-md transition-all ${
                  activeScribeId === apt.id
                    ? "border-violet-300 shadow-violet-100"
                    : ""
                }`}
              >
                <CardContent className="p-5 flex items-center justify-between">
                  <div>
                    <p className="font-medium text-slate-900">{apt.reason}</p>
                    <div className="flex items-center gap-3 text-sm text-slate-500 mt-1">
                      <span className="flex items-center gap-1">
                        <CalendarDays className="h-3 w-3" />
                        {apt.appointmentDate}
                      </span>
                      <span className="flex items-center gap-1">
                        <Clock className="h-3 w-3" />
                        {apt.timeSlot}
                      </span>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge
                      className={`${sc[apt.status] || ""} border-0 font-medium`}
                    >
                      {apt.status}
                    </Badge>
                    {apt.status === "CONFIRMED" && (
                      <Button
                        size="sm"
                        className="bg-blue-600 hover:bg-blue-700 text-white shadow-sm font-medium"
                        onClick={() => upd(apt.id, "IN_PROGRESS")}
                      >
                        Start
                      </Button>
                    )}
                    {apt.status === "IN_PROGRESS" && (
                      <Button
                        size="sm"
                        className="bg-emerald-600 hover:bg-emerald-700 text-white shadow-sm font-medium"
                        onClick={() => upd(apt.id, "COMPLETED")}
                      >
                        Complete
                      </Button>
                    )}
                    {(apt.status === "IN_PROGRESS" ||
                      apt.status === "COMPLETED") && (
                      <Button
                        size="sm"
                        variant={
                          activeScribeId === apt.id ? "default" : "outline"
                        }
                        className={
                          activeScribeId === apt.id
                            ? "bg-gradient-to-r from-violet-600 to-purple-600 hover:from-violet-700 hover:to-purple-700 text-white shadow-sm font-medium"
                            : "border-violet-200 text-violet-600 hover:bg-violet-50 font-medium"
                        }
                        onClick={() => toggleScribe(apt.id)}
                      >
                        <FileText className="h-3.5 w-3.5 mr-1.5" />
                        AI Scribe
                      </Button>
                    )}
                  </div>
                </CardContent>
              </Card>

              {/* AI Medical Scribe Panel */}
              {activeScribeId === apt.id && (
                <Card className="mt-1 bg-gradient-to-br from-violet-50 via-white to-purple-50 border-violet-200/60 shadow-sm overflow-hidden animate-in slide-in-from-top-2 duration-300">
                  <div className="p-5 border-b border-violet-100/60">
                    <div className="flex items-center justify-between">
                      <h3 className="text-sm font-semibold text-slate-900 flex items-center gap-2">
                        <div className="h-7 w-7 rounded-lg bg-gradient-to-br from-violet-600 to-purple-600 flex items-center justify-center">
                          <ClipboardList className="h-3.5 w-3.5 text-white" />
                        </div>
                        AI Medical Scribe
                        <span className="text-[10px] font-medium text-violet-600 bg-violet-100 px-2 py-0.5 rounded-full uppercase tracking-wide">
                          SOAP
                        </span>
                      </h3>
                      <button
                        onClick={() => toggleScribe(apt.id)}
                        className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors"
                      >
                        <X className="h-4 w-4" />
                      </button>
                    </div>
                    <p className="text-xs text-slate-500 mt-1.5 ml-9">
                      Type your raw consultation notes and the AI will format
                      them into a structured SOAP clinical document.
                    </p>
                  </div>
                  <CardContent className="p-5">
                    {/* Input */}
                    <div className="space-y-3">
                      <textarea
                        value={scribeNotes}
                        onChange={(e) => {
                          setScribeNotes(e.target.value);
                          setScribeError("");
                        }}
                        onKeyDown={(e) => {
                          if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
                            e.preventDefault();
                            generateSOAP();
                          }
                        }}
                        placeholder='e.g. "Patient reports persistent dry cough x 5 days, mild sore throat, no fever. Throat slightly red, lungs clear. Likely viral pharyngitis. Advised warm saline gargles, rest. Prescribed Cetirizine 10mg OD x 5 days, cough syrup. Follow up in 1 week if no improvement."'
                        rows={4}
                        className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-violet-500/20 focus:border-violet-400 resize-none transition-all"
                        disabled={scribeLoading}
                      />
                      <div className="flex items-center justify-between">
                        <p className="text-[11px] text-slate-400">
                          {scribeNotes.trim().length < 10
                            ? "Minimum 10 characters required"
                            : `${scribeNotes.trim().length} characters · Press ⌘+Enter to generate`}
                        </p>
                        <Button
                          onClick={generateSOAP}
                          disabled={
                            scribeLoading || scribeNotes.trim().length < 10
                          }
                          className="bg-gradient-to-r from-violet-600 to-purple-600 hover:from-violet-700 hover:to-purple-700 text-white shadow-lg shadow-violet-600/25 h-9 px-5 rounded-xl font-semibold text-xs"
                        >
                          {scribeLoading ? (
                            <Loader2 className="h-3.5 w-3.5 animate-spin mr-1.5" />
                          ) : (
                            <Sparkles className="h-3.5 w-3.5 mr-1.5" />
                          )}
                          {scribeLoading ? "Generating..." : "Generate SOAP Note"}
                        </Button>
                      </div>
                    </div>

                    {/* Error */}
                    {scribeError && (
                      <div className="mt-4 p-3 rounded-xl bg-red-50 border border-red-100 text-sm text-red-600 flex items-center gap-2">
                        <AlertTriangle className="h-4 w-4 flex-shrink-0" />
                        {scribeError}
                      </div>
                    )}

                    {/* SOAP Result */}
                    {soapResult && (
                      <div className="mt-5 space-y-3 animate-in fade-in slide-in-from-bottom-2 duration-300">
                        {/* Summary Banner */}
                        <div className="p-3 rounded-xl bg-violet-50 border border-violet-100 flex items-center justify-between gap-3">
                          <p className="text-sm text-violet-700 font-medium">
                            📋 {soapResult.summary}
                          </p>
                          <Button
                            size="sm"
                            variant="outline"
                            className="border-violet-200 text-violet-600 hover:bg-violet-100 h-7 text-xs font-medium flex-shrink-0"
                            onClick={copySOAP}
                          >
                            {copied ? (
                              <Check className="h-3 w-3 mr-1" />
                            ) : (
                              <Copy className="h-3 w-3 mr-1" />
                            )}
                            {copied ? "Copied!" : "Copy All"}
                          </Button>
                        </div>

                        {/* SOAP Sections */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                          {[
                            {
                              label: "Subjective",
                              icon: "🗣️",
                              content: soapResult.subjective,
                              color: "blue",
                            },
                            {
                              label: "Objective",
                              icon: "🔬",
                              content: soapResult.objective,
                              color: "emerald",
                            },
                            {
                              label: "Assessment",
                              icon: "🩺",
                              content: soapResult.assessment,
                              color: "amber",
                            },
                            {
                              label: "Plan",
                              icon: "📝",
                              content: soapResult.plan,
                              color: "violet",
                            },
                          ].map((section) => (
                            <div
                              key={section.label}
                              className="p-4 rounded-xl bg-white border border-slate-200 shadow-sm"
                            >
                              <div className="flex items-center gap-2 mb-2">
                                <span className="text-sm">{section.icon}</span>
                                <h4
                                  className={`text-xs font-bold uppercase tracking-wider text-${section.color}-600`}
                                >
                                  {section.label}
                                </h4>
                              </div>
                              <p className="text-sm text-slate-700 leading-relaxed">
                                {section.content}
                              </p>
                            </div>
                          ))}
                        </div>

                        {/* Disclaimer */}
                        <p className="text-[11px] text-slate-400 text-center">
                          ⚕️ AI-generated clinical documentation. Please review
                          and verify before adding to medical records.
                        </p>
                      </div>
                    )}
                  </CardContent>
                </Card>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
