package com.nexushealth.repository;

import com.nexushealth.entity.Appointment;
import com.nexushealth.entity.enums.AppointmentStatus;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

@Repository
public interface AppointmentRepository
    extends JpaRepository<Appointment, UUID>
{
    List<Appointment> findByPatientId(UUID patientId);
    List<Appointment> findByDoctorId(UUID doctorId);
    List<Appointment> findByDoctorIdAndAppointmentDateAndStatusNot(
        UUID doctorId,
        LocalDate date,
        AppointmentStatus status
    );
    boolean existsByDoctorIdAndAppointmentDateAndTimeSlotAndStatusNot(
        UUID doctorId,
        LocalDate date,
        LocalTime slot,
        AppointmentStatus status
    );

    /** Sum of amounts for all COMPLETED appointments — total platform revenue. */
    @Query(
        "SELECT COALESCE(SUM(a.amount), 0) FROM Appointment a WHERE a.status = 'COMPLETED'"
    )
    BigDecimal getTotalRevenue();

    /** Get revenue generated by each doctor */
    @Query("SELECT d.fullName, SUM(a.amount) FROM Appointment a JOIN a.doctor d WHERE a.status = 'COMPLETED' GROUP BY d.id, d.fullName ORDER BY SUM(a.amount) DESC")
    List<Object[]> getRevenueByDoctorRaw();

    /** Find appointments where the patient has joined the video call waiting room. */
    List<Appointment> findByDoctorIdAndPatientJoinedTrue(UUID doctorId);
}
